#version: "3.8"

services:

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress_sb
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_pass


  nginx:
   build: ./requirements/nginx
   ports:
           - "443:443"
   volumes:
           - wordpress:/var/www/html
   networks:
           - inception
   restart: always

  wordpress:
   build: ./requirements/wordpress
   depends_on:
           - mariadb
   volumes:
           - wordpress:/var/www/html
   networks:
           - inception
   restart: always
#   environment:
#      - MYSQL_ROOT_PASSWORD=root_pass
#      - MYSQL_DATABASE=wordpress_sb
#      - MYSQL_USER=wp_user
#      - MYSQL_PASSWORD=wp_pass
#      - ADMIN_USER=adminuser
#      - ADMIN_PASSWORD=supersecurepassword
#      - ADMIN_EMAIL=iniska@student.hive.fi
   env_file:
      - .env

networks:
  inception:

# store database. no dataloss when restart
volumes:
   wordpress:
   mariadb:
